In [1]:
import numpy as np

In [2]:
c = np.array([1,2,3])
print(c.shape)

(3,)


In [3]:
print(c[0])

1


In [6]:
r = np.array([[1,2,3]])
print(r.shape)

(1, 3)


array([[1, 2, 3]])

In [8]:
print(r[0,1])

2


In [10]:
a = np.zeros((2,2))
print(a)

b = np.ones((2,2))
print(b)

c = np.full((2,2), 7)
print(c)

d = np.random.random((2,2))
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[0.35702477 0.79569543]
 [0.38811579 0.0720635 ]]


In [12]:
A = np.array([[1,2],[3,4],[5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
B = np.array([[11,12,13,14],[15,16,17,18]])
B

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [14]:
A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [17]:
# 행렬의 곱
np.dot(A,B)

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

In [18]:
np.dot(B,A)

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [19]:
A = np.array([[60,5.5,1],[65,5.0,0],[55,6.0,1]])
B = np.array([66,70,78])

In [20]:
eye3 = np.eye(3)
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
from numpy.linalg import inv
A_inv = inv(A)
A_inv

array([[ 0.08695652,  0.00869565, -0.08695652],
       [-1.13043478,  0.08695652,  1.13043478],
       [ 2.        , -1.        , -1.        ]])

In [22]:
A*A_inv

array([[ 5.21739130e+00,  4.78260870e-02, -8.69565217e-02],
       [-7.34782609e+01,  4.34782609e-01,  0.00000000e+00],
       [ 1.10000000e+02, -6.00000000e+00, -1.00000000e+00]])

In [23]:
A.dot(A_inv)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.22044605e-16,  1.00000000e+00, -2.22044605e-16],
       [-4.44089210e-16,  0.00000000e+00,  1.00000000e+00]])

In [25]:
x = A_inv.dot(B)
x

array([ -0.43478261,  19.65217391, -16.        ])

In [26]:
from numpy.linalg import solve

x = solve(A,B)
x

array([ -0.43478261,  19.65217391, -16.        ])